### ISSUE TITLE
No bug reporting option in README file

### ISSUE THREAD

**Issue by badone** [whoshuu/cpr-example#4]
The readme ends with "If you do use it and find bugs you'd like to report, see below!" but there is nothing "below" :)

**Comment by whoshuu** [comment]
Thanks for the comment @badone, I'll resolve this :smile:

**Comment by badone** [comment]
@whoshuu No problem, used the library yesterday to write a basic (and raw) (swift) object storage workload generator - https://github.com/badone/iobject
Found cpr easy to use and quite enjoyed the whole process :)
Nice work.
