### ISSUE TITLE
Example.cpp response 0 when making HTTPS GET to some other website

### ISSUE THREAD

**Issue by Jason-Gew** [whoshuu/cpr-example#5]
Hi,

We tried changing the url in example.cpp to some other websites, but even the status_code return "0" instead of the correct code "200". But also when using HTTPS POST, the response is not very correct.

Is there any ideas with this problem?

Best Regards!

**Comment by yoni386** [comment]
I saw it too. I think curl-config doesn't include SSL or you are not using the right curl.

**Comment by paulo-erichsen** [comment]
you need to pass in `cpr::VerifySsl(false)`
